version: '3'
services:
  php:
    tty: true
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - ENV=dev
      - PHP_IDE_CONFIG=serverName=docker